"""alterando relacionamento do usuario e participante para many-to-one & adicionando nome aos participantes

Revision ID: 440def5f382d
Revises: b57080a06872
Create Date: 2025-05-07 19:10:29.805303

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '440def5f382d'
down_revision: Union[str, None] = 'b57080a06872'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('participante', sa.Column('nome', sa.String(), server_default='Participante', nullable=False))
    op.drop_constraint('participante_id_usuario_key', 'participante', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('participante_id_usuario_key', 'participante', ['id_usuario'])
    op.drop_column('participante', 'nome')
    # ### end Alembic commands ###
