"""add_relationship_usuario_vocalizacao

Revision ID: b57080a06872
Revises: d6c88cb0b081
Create Date: 2025-04-14 22:46:56.253641

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b57080a06872'
down_revision: Union[str, None] = 'd6c88cb0b081'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('audio_id_vocalizacao_fkey', 'audio', type_='foreignkey')
    op.create_foreign_key(None, 'audio', 'vocalizacao', ['id_vocalizacao'], ['id'], ondelete='CASCADE')
    op.add_column('vocalizacao', sa.Column('id_usuario', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'vocalizacao', 'usuario', ['id_usuario'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'vocalizacao', type_='foreignkey')
    op.drop_column('vocalizacao', 'id_usuario')
    op.drop_constraint(None, 'audio', type_='foreignkey')
    op.create_foreign_key('audio_id_vocalizacao_fkey', 'audio', 'vocalizacao', ['id_vocalizacao'], ['id'])
    # ### end Alembic commands ###
