"""Add created_at & updated_at ao participante

Revision ID: d01e76548d93
Revises: bc6f067cb8c2
Create Date: 2025-01-15 18:45:19.237152

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd01e76548d93'
down_revision: Union[str, None] = 'bc6f067cb8c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('participante', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('participante', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('participante', 'updated_at')
    op.drop_column('participante', 'created_at')
    # ### end Alembic commands ###
