"""Add on delete cascade to usuario participante audio

Revision ID: d6c88cb0b081
Revises: e443932a272f
Create Date: 2025-04-11 19:48:19.171379

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd6c88cb0b081'
down_revision: Union[str, None] = 'e443932a272f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('audio_id_usuario_fkey', 'audio', type_='foreignkey')
    op.drop_constraint('audio_id_participante_fkey', 'audio', type_='foreignkey')
    op.create_foreign_key(None, 'audio', 'usuario', ['id_usuario'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'audio', 'participante', ['id_participante'], ['id'], ondelete='CASCADE')
    op.drop_constraint('participante_id_usuario_fkey', 'participante', type_='foreignkey')
    op.create_foreign_key(None, 'participante', 'usuario', ['id_usuario'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'participante', type_='foreignkey')
    op.create_foreign_key('participante_id_usuario_fkey', 'participante', 'usuario', ['id_usuario'], ['id'])
    op.drop_constraint(None, 'audio', type_='foreignkey')
    op.drop_constraint(None, 'audio', type_='foreignkey')
    op.create_foreign_key('audio_id_participante_fkey', 'audio', 'participante', ['id_participante'], ['id'])
    op.create_foreign_key('audio_id_usuario_fkey', 'audio', 'usuario', ['id_usuario'], ['id'])
    # ### end Alembic commands ###
