"""Add aceite_termos bool to usuario

Revision ID: e443932a272f
Revises: 60d453f57982
Create Date: 2025-01-31 20:05:07.515555

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e443932a272f'
down_revision: Union[str, None] = '60d453f57982'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuario', sa.Column('aceite_termos', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuario', 'aceite_termos')
    # ### end Alembic commands ###
